robot_name: pitop_robot
logging_folder: logs

sensors:
  lidar:
    name: pitop_lidar
    driver: rplidar
    parameters:
      port: /dev/ttyUSB0
      baudrate: 115200
    pose:
      xyz: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]

  compass:
    name: pitop_compass
    driver: pitop_compass
    pose:
      xyz: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]

  encoder:
    name: pitop_encoder
    driver: pitop_encoder
    parameters:
      wheel_separation: 0.163
      left:
        port: M3
        invert: false
        wheel_diameter: 0.072
      right:
        port: M0
        invert: true
        wheel_diameter: 0.072
    pose:
      xyz: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]

  external_positioning:
    name: aruco_marker
    driver: aruco_udp
    parameters:
      port: 50000
      timeout: 15
      marker_id: 1
    pose:
      xyz: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]

control:
  mission:
    name: square_1m.yaml
    parameters:
      waypoint_acceptance_radius: 0.1
      loop_waypoints: false
  localisation:
    name: localisation
    driver: dead_reckoning
  navigation:
    name: navigation
    driver: naive_rotate_move
    parameters:
      linear_speed: 0.2 # m/s
      rotation_speed: 0.5 # rad/s
      orientation_threshold: 0.1  # radians


motors:
  name: pitop_motors
  driver: pitop_motors
  parameters:
    wheel_separation: 0.163
    left:
      port: M3
      invert: false
      wheel_diameter: 0.072
    right:
      port: M0
      invert: true
      wheel_diameter: 0.072