#Assuming X is northings and Y is eastings, following data given from lab / navigation assignment
waypoints:
  - [-2, 1]
  - [2, 1]
  - [2, 2]
  - [-2, 2]
  - [-2, 3]
  - [2, 3]
  - [2, 4]
  - [0, 4]
  - [0, 0]